/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PAdministrativeRole;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author abdulla
 */
public class PoliceReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PoliceReportsJPanel
     */
    private JPanel userProcessContainer;
    public PoliceReportsJPanel( JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barPanel = new javax.swing.JPanel();
        linePanel = new javax.swing.JPanel();
        piePanel = new javax.swing.JPanel();
        backJButton = new javax.swing.JButton();
        btninmates = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnarrest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        barPanel.setBackground(new java.awt.Color(153, 255, 153));
        barPanel.setLayout(new java.awt.BorderLayout());

        linePanel.setBackground(new java.awt.Color(0, 153, 153));
        linePanel.setLayout(new java.awt.BorderLayout());

        piePanel.setBackground(new java.awt.Color(153, 255, 204));
        piePanel.setLayout(new java.awt.BorderLayout());

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        btninmates.setText("View");
        btninmates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninmatesActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Total Inmates Reports :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total Arrest Reports :");

        btnarrest.setText("View");
        btnarrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarrestActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Police Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(linePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(piePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(688, 688, 688)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnarrest, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btninmates, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 660, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(backJButton)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnarrest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btninmates)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(piePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btninmatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninmatesActionPerformed

        DefaultCategoryDataset bardataset = new DefaultCategoryDataset();

        bardataset.setValue(210,"FELONS", "2018");
        bardataset.setValue(435,"FELONS", "2019");
        bardataset.setValue(615,"FELONS", "2020");

        JFreeChart bar = ChartFactory.createBarChart3D("Inmates Count for 2018-2020", "YEARS", "INMATES", bardataset,PlotOrientation.VERTICAL, true,true,false);
        CategoryPlot p = (CategoryPlot)bar.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLUE);
        ChartPanel barPan = new ChartPanel(bar);
        barPanel.removeAll();
        barPanel.add(barPan,BorderLayout.CENTER);
        barPanel.validate();

        DefaultCategoryDataset linedataset = new DefaultCategoryDataset();

        linedataset.setValue(210,"FELONS", "2018");
        linedataset.setValue(435,"FELONS", "2019");
        linedataset.setValue(615,"FELONS", "2020");

        JFreeChart line = ChartFactory.createLineChart("Inmates Count for 2018-2020", "YEARS", "INMATES", linedataset,PlotOrientation.VERTICAL, true,true,false);
        CategoryPlot p1 = (CategoryPlot)line.getCategoryPlot();
        p1.setRangeGridlinePaint(Color.YELLOW);
        ChartPanel linePan = new ChartPanel(line);

        linePanel.removeAll();
        linePanel.add(linePan,BorderLayout.CENTER);
        linePanel.validate();

        DefaultPieDataset piedataset = new DefaultPieDataset();
        
        piedataset.setValue("2018", 210);
        piedataset.setValue("2019", 435);
        piedataset.setValue("2020", 615);

        JFreeChart pieChart = ChartFactory.createPieChart3D("Inmates Count for 2018-2020", piedataset,true,true,true);

        PiePlot3D Pie = (PiePlot3D)pieChart.getPlot();

        ChartPanel piepan = new ChartPanel(pieChart);

        piePanel.removeAll();
        piePanel.add(piepan,BorderLayout.CENTER);
        piePanel.validate();
    }//GEN-LAST:event_btninmatesActionPerformed

    private void btnarrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarrestActionPerformed

        DefaultCategoryDataset bardataset = new DefaultCategoryDataset();
 
        bardataset.setValue(400,"CRIMINALS", "2018");
        bardataset.setValue(270,"CRIMINALS", "2019");
        bardataset.setValue(800,"CRIMINALS", "2020");

        JFreeChart bar = ChartFactory.createBarChart3D("Total Criminals Arredted for 2018-2020", "YEARS", "CRIMINALS", bardataset,PlotOrientation.VERTICAL, true,true,false);
        CategoryPlot p = (CategoryPlot)bar.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLUE);
        ChartPanel barPan = new ChartPanel(bar);
        barPanel.removeAll();
        barPanel.add(barPan,BorderLayout.CENTER);
        barPanel.validate();

        DefaultCategoryDataset linedataset = new DefaultCategoryDataset();
 
        linedataset.setValue(400,"CRIMINALS", "2018");
        linedataset.setValue(270,"CRIMINALS", "2019");
        linedataset.setValue(800,"CRIMINALS", "2020");

        JFreeChart line = ChartFactory.createLineChart("Total Criminals Arredted for 2018-2020", "YEARS", "CRIMINALS", linedataset,PlotOrientation.VERTICAL, true,true,false);
        CategoryPlot p1 = (CategoryPlot)line.getCategoryPlot();
        p1.setRangeGridlinePaint(Color.YELLOW);
        ChartPanel linePan = new ChartPanel(line);

        linePanel.removeAll();
        linePanel.add(linePan,BorderLayout.CENTER);
        linePanel.validate();

        DefaultPieDataset piedataset = new DefaultPieDataset();
        
        piedataset.setValue("2018", 400);
        piedataset.setValue("2019", 270);
        piedataset.setValue("2020", 800);

        JFreeChart pieChart = ChartFactory.createPieChart3D("Total Criminals Arredted for 2018-2020", piedataset,true,true,true);

        PiePlot3D Pie = (PiePlot3D)pieChart.getPlot();

        ChartPanel piepan = new ChartPanel(pieChart);

        piePanel.removeAll();
        piePanel.add(piepan,BorderLayout.CENTER);
        piePanel.validate();
    }//GEN-LAST:event_btnarrestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JPanel barPanel;
    private javax.swing.JButton btnarrest;
    private javax.swing.JButton btninmates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel linePanel;
    private javax.swing.JPanel piePanel;
    // End of variables declaration//GEN-END:variables
}
