/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SocialWorkerRole;

import Business.Case.Case;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akanksha
 */
public class ReportStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportStatusJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;

    public ReportStatusJPanel(JPanel userProcessContainer, EcoSystem business, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        tblReports.getTableHeader().setForeground(Color.blue);
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblReports.getModel();
        model.setRowCount(0);
        for (Case c : business.getCaseDir().getCaseList()) {
            if (c.getStatus().equals("ReportSent")) {
                Object[] row = new Object[5];
                row[0] = c;
//                row[1] = c.getVictimName();
                row[1] = c.getSocialObservations();
                row[2] = c.getDetails();
                row[3] = c.getIssue();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        btnViewHospStatus = new javax.swing.JButton();
        btnViewLawstatus = new javax.swing.JButton();
        btnViewPoliceStatus = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeading.setText("List of reports");

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Case ID", "Observations", "Description", "Issue"
            }
        ));
        tblReports.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tblReports.setSelectionForeground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(tblReports);

        btnViewHospStatus.setBackground(new java.awt.Color(255, 255, 255));
        btnViewHospStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewHospStatus.setText("View Hospital Report");
        btnViewHospStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospStatusActionPerformed(evt);
            }
        });

        btnViewLawstatus.setBackground(new java.awt.Color(255, 255, 255));
        btnViewLawstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewLawstatus.setText("View Lawfirm Report");
        btnViewLawstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLawstatusActionPerformed(evt);
            }
        });

        btnViewPoliceStatus.setBackground(new java.awt.Color(255, 255, 255));
        btnViewPoliceStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewPoliceStatus.setText("View Police Report");
        btnViewPoliceStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPoliceStatusActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addContainerGap(1090, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewHospStatus)
                .addGap(99, 99, 99)
                .addComponent(btnViewLawstatus)
                .addGap(92, 92, 92)
                .addComponent(btnViewPoliceStatus)
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewHospStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewLawstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPoliceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnViewPoliceStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPoliceStatusActionPerformed
int selectedRow = tblReports.getSelectedRow();
          
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a case", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
            Case c=(Case) tblReports.getValueAt(selectedRow, 0);

        ViewPoliceStatsJPanel viewPStatus = new ViewPoliceStatsJPanel(userProcessContainer, business, userAccount,c.getCaseID()+"");
        userProcessContainer.add("ViewPoliceStatsJPanel", viewPStatus);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPoliceStatusActionPerformed

    private void btnViewHospStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospStatusActionPerformed

         int selectedRow = tblReports.getSelectedRow();
          
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a case", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
            Case c=(Case) tblReports.getValueAt(selectedRow, 0);
        
        ViewHospStatusJPanel viewHStatus = new ViewHospStatusJPanel(userProcessContainer, business, userAccount,c.getCaseID()+"");
        userProcessContainer.add("ViewHospStatusJPanel", viewHStatus);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewHospStatusActionPerformed

    private void btnViewLawstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLawstatusActionPerformed
         int selectedRow = tblReports.getSelectedRow();
          
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a case", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
            Case c=(Case) tblReports.getValueAt(selectedRow, 0);
        ViewLawStatsJPanel viewLStatus = new ViewLawStatsJPanel(userProcessContainer, business, userAccount,c.getCaseID()+"");
        userProcessContainer.add("ViewLawStatsJPanel", viewLStatus);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewLawstatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnViewHospStatus;
    private javax.swing.JButton btnViewLawstatus;
    private javax.swing.JButton btnViewPoliceStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JTable tblReports;
    // End of variables declaration//GEN-END:variables
}
